// Cross-test: 180 JS-generated fixtures vs Rust damage_calc.
// Fixtures generated by tools/generate-fixtures.js.
// Run: cargo test --test test_damage_calc

use oxark::damage_calc::{damage_calc_with_action_types, Winner};
use serde::Deserialize;

const FIXTURES_JSON: &str = include_str!("../../../../../fixtures/damage_calc.json");

#[derive(Deserialize)]
struct Expected {
    winner: String, // "p1" | "p2"
    p1_bp_total: u32,
    p2_bp_total: u32,
    looted_card_id: u8,
}

#[derive(Deserialize)]
struct Fixture {
    card_ids_p1: [u64; 10],
    card_ids_p2: [u64; 10],
    action_types_p1: [u8; 5],
    action_types_p2: [u8; 5],
    seed: [u8; 32],
    expected: Expected,
}

#[test]
fn damage_calc_cross_test() {
    let fixtures: Vec<Fixture> =
        serde_json::from_str(FIXTURES_JSON).expect("failed to parse damage_calc.json");

    assert!(!fixtures.is_empty(), "fixture file is empty");

    for (i, f) in fixtures.iter().enumerate() {
        let result = damage_calc_with_action_types(
            &f.card_ids_p1,
            &f.card_ids_p2,
            &f.action_types_p1,
            &f.action_types_p2,
            &f.seed,
        );

        let expected_winner = match f.expected.winner.as_str() {
            "p1" => Winner::P1,
            "p2" => Winner::P2,
            other => panic!("fixture {i}: unknown winner '{other}'"),
        };

        assert_eq!(
            result.winner,
            expected_winner,
            "fixture {i}: winner — p1_ids={:?} p2_ids={:?} at1={:?} at2={:?}",
            &f.card_ids_p1[..5],
            &f.card_ids_p2[..5],
            f.action_types_p1,
            f.action_types_p2,
        );
        assert_eq!(
            result.p1_bp_total, f.expected.p1_bp_total,
            "fixture {i}: p1_bp_total",
        );
        assert_eq!(
            result.p2_bp_total, f.expected.p2_bp_total,
            "fixture {i}: p2_bp_total",
        );
        assert_eq!(
            result.looted_card_id, f.expected.looted_card_id,
            "fixture {i}: looted_card_id",
        );
    }

    println!(
        "damage_calc cross-test: {}/{} fixtures passed",
        fixtures.len(),
        fixtures.len()
    );
}
