[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.localnet]
oxark = "FUNza8fK4aUtGrf2jaeBomZbyScmZmfrx2r6jbZaDx76"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "cargo test"

[hooks]
