[package]
name = "oxark-tests"
version = "0.1.0"
edition = "2021"

[[test]]
name = "test_game"
path = "test_game.rs"

[[test]]
name = "v3_plus_mechanics"
path = "v3_plus_mechanics.rs"

[[test]]
name = "claim_battle_loot"
path = "claim_battle_loot.rs"

[dependencies]
sha2 = "0.10"
oxark = { path = "../programs/oxark", features = ["no-entrypoint"] }
anchor-lang = "1.0.0"

[dev-dependencies]
litesvm = "0.10.0"
solana-message = "3.0.1"
solana-transaction = "3.0.2"
solana-signer = "3.0.0"
solana-keypair = "3.0.1"
solana-pubkey = "3.0.0"
solana-sdk-ids = "3.0.0"
solana-instruction = "3.0.0"

[lints.rust]
unexpected_cfgs = { level = "warn", check-cfg = ['cfg(target_os, values("solana"))'] }
